# Generated by Django 3.0.6 on 2020-06-11 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20200217_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='templates/no-image-icon-17.jpg', upload_to='images/'),
        ),
    ]
